# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Detail

# Model Form Field configuration
form: $/arteriaweb/foodbug/models/detail/fields.yaml

# Model Class name
modelClass: Arteriaweb\Foodbug\Models\Detail

# Default redirect location
defaultRedirect: arteriaweb/foodbug/details

# Create page
create:
    title: Create Detail
    redirect: arteriaweb/foodbug/details/update/:id
    redirectClose: arteriaweb/foodbug/details

# Update page
update:
    title: Edit Detail
    redirect: arteriaweb/foodbug/details
    redirectClose: arteriaweb/foodbug/details

# Preview page
preview:
    title: Preview Detail
